// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXBa4RL_xmDc4iHhjdh5HsNl7t3eDGy0s',
    appId: '1:308613554777:web:49b6f14c09d2561a2a0748',
    messagingSenderId: '308613554777',
    projectId: 'flutter-push-notificatio-3d58f',
    authDomain: 'flutter-push-notificatio-3d58f.firebaseapp.com',
    storageBucket: 'flutter-push-notificatio-3d58f.appspot.com',
    measurementId: 'G-JCTRWVNK82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYIHrufZJ6NV5T0yCYrKi1y87xzStwNL8',
    appId: '1:308613554777:android:c353207f8106e5b42a0748',
    messagingSenderId: '308613554777',
    projectId: 'flutter-push-notificatio-3d58f',
    storageBucket: 'flutter-push-notificatio-3d58f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY7Fb6UjBqqr8rJW_mE-kcbcQ2dwqdzRg',
    appId: '1:308613554777:ios:12f801c09e33fde42a0748',
    messagingSenderId: '308613554777',
    projectId: 'flutter-push-notificatio-3d58f',
    storageBucket: 'flutter-push-notificatio-3d58f.appspot.com',
    iosClientId: '308613554777-r1j6tmishsl8tpjrldfgjomctahvsbqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPushNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY7Fb6UjBqqr8rJW_mE-kcbcQ2dwqdzRg',
    appId: '1:308613554777:ios:12f801c09e33fde42a0748',
    messagingSenderId: '308613554777',
    projectId: 'flutter-push-notificatio-3d58f',
    storageBucket: 'flutter-push-notificatio-3d58f.appspot.com',
    iosClientId: '308613554777-r1j6tmishsl8tpjrldfgjomctahvsbqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPushNotifications',
  );
}
